server:
  port: 8080
  servlet:
    context-path: /
  name: hello-world
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/xdclass?serverTimezone=Asia/Shanghai&characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false
    username: root
    password: qqhilvMgAl@7
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled : true
      max-file-size: "256MB"
      max-request-size: "256MB"
  mybatis-plus:
    #global-config:
      #db-config:
        #id-type: ASSIGN_ID
    typeEnumsPackage: indi.zhifa.learn.xdclass.busy.eneity.enums
    #configuration:
      #default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

swagger:
    enable: true
    group-name: "业务接口"
    api-package: indi.zhifa.learn.jenkins.helloworld.controller.view;indi.zhifa.learn.jenkins.helloworld.controller.api
    api-regex: "/api/**"
    title: "小D课堂业务接口"
    description: "小D课堂业务接口文档"
    version: "1.0.0"
    name: "芝法酱"
    email: "hataksumo@163.com"
    url: "https://github.com/hataksumo"
app:
  security:
    token:
      secret: qqhilvMgAl@7
      duration: 7200
    passwd:
      strength: 5
    verify-code:
      expire: 86400
  user:
    max-address: 20
minio:
  endpoint: http://localhost:9000
  bucketName: xdclass
  accessKey: MITXOGU3HLK03XA1XC75 #访问的key
  secretKey: Bg4vbT7LGV6AJ70wb3yKZRRhygssSb5s3db0SNt1 #访问的秘钥